language: java
sudo: false
script:
  - mvn install -B -V
  - mvn javadoc:javadoc

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
