language: java
jdk:
  - openjdk11
sudo: false
script: ./gradlew build --stacktrace
after_success: ./gradlew javadoc

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build/docs/javadoc
  github-token: $DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
